### ISSUE TITLE
Crash while playing as Gourmand and saving in an OE special gate

### ISSUE THREAD

**Issue by TYTheBeast** [MatheusVigaro/DressMySlugcat#1]
`FutileException: Duplicate element name 'dressmyslugcat_dressmyslugcat.cloakgry_OnTopOfTerrainHand' found! All element names must be unique!
FAtlasManager.AddAtlas (FAtlas atlas) (at <41a4743dd7114320b03bb7d1f362c0b7>:0)
FAtlasManager.ActuallyLoadAtlasOrImage (System.String name, System.String imagePath, System.String dataPath) (at <41a4743dd7114320b03bb7d1f362c0b7>:0)
FAtlasManager.LoadAtlas (System.String atlasPath) (at <41a4743dd7114320b03bb7d1f362c0b7>:0)
DressMySlugcat.Hooks.AtlasHooks.LoadAtlasesInternal (System.String directory) (at <36a910974c724eb8b090c88b2869f92c>:0)
UnityEngine.Debug:LogException(Exception)
DressMySlugcat.Hooks.AtlasHooks:RegisterError(String, Exception)
DressMySlugcat.Hooks.AtlasHooks:LoadAtlasesInternal(String)
DressMySlugcat.Hooks.AtlasHooks:LoadAtlases(String)
DressMySlugcat.Hooks.AtlasHooks:LoadAtlasesInternal(String)
DressMySlugcat.Hooks.AtlasHooks:LoadAtlases(String)
DressMySlugcat.Plugin:RainWorld_PostModsInit(orig_PostModsInit, RainWorld)
DMD<>?748306944:Hook<RainWorld::PostModsInit>?-1966699520(RainWorld)
DMD<>?748306944:Trampoline<RainWorld::PostModsInit>?1757864448(RainWorld)
RebindDevTools.Hooks:RainWorld_PostModsInit(orig_PostModsInit, RainWorld)
DMD<>?748306944:Hook<RainWorld::PostModsInit>?-1047997952(RainWorld)
DMD<>?748306944:Trampoline<RainWorld::PostModsInit>?2017826816(RainWorld)
SBCameraScroll.MainMod:RainWorld_PostModsInit(orig_PostModsInit, RainWorld)
DMD<>?748306944:Hook<RainWorld::PostModsInit>?1531774976(RainWorld)
Menu.InitializationScreen:Update()
MainLoopProcess:RawUpdate(Single)
ProcessManager:Update(Single)
RainWorld:Update()`

The crash occured on mod version 1.1.0, and I've noticed that the latest version as of right now is 1.1.4, so if the crash report isn't relevant anymore, I apologize for the outdated report. If any more info is needed, like my list of mods, please let me know. This is using the non-steam version of the game.

**Comment by MatheusVigaro** [comment]
If the issue is happening after you started the game, then this is unrelated to DMS, even though you have a DMS error on your exceptionLog. The atlases are only loaded during startup, and the exceptions (in this case caused by a mod which has duplicate sprites) are logged, but wouldn't actually cause a crash since they're being handled, if you are still having this issue, I'd recommend going to the Rain World Discord server.
